package com.example.agriafrica.navigation

const val HOME_URL = "home"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"
const val MORE_URL = "more"
const val ABOUT_URL = "about"
const val VIEW_USER_PRODUCT = "view_user_products"
const val ROUTE_UPDATE_PRODUCTS = "update_product"
const val ADD_TASK = "add_task"
const val VIEW_TASKS = "view_task"
const val ADD_ANIMAL = "add_animal"
const val VIEW_ANIMAL = "view_animal"
const val VIEW_CROP = "view_crop"
const val ADD_CROP = "add_crop"
const val UPDATE_TASK = "update_task"
const val UPDATE_CROP = "update_crop"
const val UPDATE_ANIMAL = "update_animal"
